Document: devpi
Title: Debian devpi Manual
Author: <insert document author here>
Abstract: This manual describes what devpi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/devpi/devpi.sgml.gz

Format: postscript
Files: /usr/share/doc/devpi/devpi.ps.gz

Format: text
Files: /usr/share/doc/devpi/devpi.text.gz

Format: HTML
Index: /usr/share/doc/devpi/html/index.html
Files: /usr/share/doc/devpi/html/*.html
